# Generated by Django 6.1 on 2026-08-28 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartmentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, verbose_name="体育部简介"),
                ),
                (
                    "welcome_slogan",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="迎新标语"
                    ),
                ),
                (
                    "recruitment_info",
                    models.TextField(blank=True, verbose_name="招新信息"),
                ),
                (
                    "contact_info",
                    models.TextField(
                        blank=True,
                        help_text="可填写经确认的邮箱、QQ群或其他公开联系方式。",
                        verbose_name="联系方式",
                    ),
                ),
                (
                    "qq_group_qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="department/qr_codes/",
                        verbose_name="QQ群二维码",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "体育部资料",
                "verbose_name_plural": "体育部资料",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="活动名称")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sports", "体育赛事"),
                            ("welcome", "迎新活动"),
                            ("team_building", "团建活动"),
                            ("birthday", "部门生日会"),
                            ("volunteer", "志愿服务"),
                            ("meeting", "会议与学习"),
                            ("other", "其他活动"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                        verbose_name="活动分类",
                    ),
                ),
                (
                    "activity_date",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="活动日期"
                    ),
                ),
                ("introduction", models.TextField(blank=True, verbose_name="活动简介")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="activities/covers/",
                        verbose_name="封面",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否展示"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "活动",
                "verbose_name_plural": "活动",
                "ordering": ("sort_order", "-activity_date", "id"),
                "indexes": [
                    models.Index(
                        fields=["is_visible", "sort_order"],
                        name="activity_visible_sort_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250, verbose_name="问题")),
                ("answer", models.TextField(verbose_name="回答")),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否展示"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "常见问题",
                "verbose_name_plural": "常见问题",
                "ordering": ("sort_order", "id"),
                "indexes": [
                    models.Index(
                        fields=["is_visible", "sort_order"], name="faq_visible_sort_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "major_class",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="专业班级"
                    ),
                ),
                ("position", models.CharField(max_length=100, verbose_name="职务")),
                (
                    "generation",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="届数",
                    ),
                ),
                (
                    "tenure",
                    models.CharField(
                        blank=True,
                        help_text="按已确认资料填写，例如“2020-2022”。",
                        max_length=100,
                        verbose_name="任期",
                    ),
                ),
                ("introduction", models.TextField(blank=True, verbose_name="个人介绍")),
                (
                    "welcome_message",
                    models.TextField(blank=True, verbose_name="新生寄语"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="members/", verbose_name="照片"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否展示"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "成员",
                "verbose_name_plural": "成员",
                "ordering": ("sort_order", "generation", "id"),
                "indexes": [
                    models.Index(
                        fields=["is_visible", "sort_order"],
                        name="member_visible_sort_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50, verbose_name="留言昵称")),
                ("content", models.TextField(verbose_name="留言内容")),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "留言",
                "verbose_name_plural": "留言",
                "ordering": ("-submitted_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["review_status", "-submitted_at"],
                        name="message_status_time_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="activities/media/", verbose_name="图片或视频"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "图片"), ("video", "视频")],
                        db_index=True,
                        default="image",
                        max_length=10,
                        verbose_name="媒体类型",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, verbose_name="说明"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="portal.activity",
                        verbose_name="所属活动",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动媒体",
                "verbose_name_plural": "活动媒体",
                "ordering": ("sort_order", "id"),
                "indexes": [
                    models.Index(
                        fields=["activity", "sort_order"],
                        name="media_activity_sort_idx",
                    )
                ],
            },
        ),
    ]
