-- Generated from seed_confirmed_content.py; do not edit by hand.
INSERT OR REPLACE INTO department_profile (id, introduction, welcome_slogan, recruitment_info, contact_info, qq_group_qr_code) VALUES (1, '体育部是学院体育活动的策划者与组织者，始终以“服务师生、丰富校园体育文化”为宗旨，用认真与热爱把每一场赛事、每一次活动办得有声有色。', '以热爱集结，为青春开赛', '体育部现面向2026级新生开展第七届成员招新。第七届成员尚未产生，具体时间、地点和报名方式以学院通知为准。', '', NULL);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (1, '廖朝瑞', '通信202', '部长', 1, '2020—2022', '', '', NULL, 101, 1);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (2, '吴家超', '电科211', '部长', 2, '2022—2023', '', '', NULL, 202, 1);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (3, '苏小曼', '通信222', '部长', 3, '2023—2024', '', '大学是一个全新的起点。请保持好奇心和开放心态，勇敢追求梦想；每一次挑战都是成长的机会，每一次努力都值得被尊重。', NULL, 303, 1);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (4, '黄流广', '通信232', '部长', 4, '2024—2025', '性格活泼开朗，喜欢听歌和旅游；曾任校全媒体干事、学院文体部干事和部长，曾获校电赛三等奖。', '时间会留下最真的痕迹，愿你的大学之路，每一步都坚实有力，饱含喜悦与成长。', NULL, 404, 1);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (5, '卢小梦', '通信242', '部长', 5, '2025—2026', '', '', NULL, 505, 1);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (6, '韦佳宜', '', '部长', 6, '2026—2027', '', '', NULL, 606, 1);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (7, '车江潮', '', '副部长', 6, '2026—2027', '', '', NULL, 607, 1);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (8, '周春合', '', '副部长', 6, '2026—2027', '', '', NULL, 608, 1);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (9, '黄惠烨', '', '副部长', 6, '2026—2027', '', '', NULL, 609, 1);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (10, '农金红', '', '副部长', 6, '2026—2027', '', '', NULL, 610, 1);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (11, '莫大深', '', '副部长', 6, '2026—2027', '', '', NULL, 611, 1);
INSERT OR REPLACE INTO members (id, name, major_class, position, generation, tenure, introduction, welcome_message, photo, sort_order, is_visible) VALUES (12, '苏光良', '', '副部长', 6, '2026—2027', '', '', NULL, 612, 1);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (1, '2025级新生迎新', 'welcome', '迎新活动', NULL, '参与学院新生迎新，为新同学提供现场引导和服务保障。', NULL, 10, 0);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (2, '干事招新与面试', 'welcome', '迎新活动', NULL, '通过公开、公平的招新与面试，让新成员了解部门并加入团队。', NULL, 20, 0);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (3, '2025级新生见面会', 'welcome', '迎新活动', NULL, '通过见面会帮助新成员认识伙伴、了解工作并融入集体。', NULL, 30, 0);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (4, '院运会', 'sports', '体育赛事', NULL, '统筹赛事策划、项目安排、人员分工和现场组织。', NULL, 40, 0);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (5, '2025年运动会工作记录', 'sports', '体育赛事', NULL, '记录运动会期间的现场工作、协作与集体时刻。', '/media/activities/confirmed/sports-work-2025/01.jpeg', 50, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (1, 5, '/media/activities/confirmed/sports-work-2025/01.jpeg', 'image', '[确认资料] 2025年运动会群体照片.jpeg', 972, 647, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (2, 5, '/media/activities/confirmed/sports-work-2025/02.jpeg', 'image', '[确认资料] 2025年运动会工作的照片.jpeg', 1599, 2132, 20);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (3, 5, '/media/activities/confirmed/sports-work-2025/03.jpeg', 'image', '[确认资料] 2025年运动会工作照.jpeg', 1599, 2132, 30);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (4, 5, '/media/activities/confirmed/sports-work-2025/04.jpeg', 'image', '[确认资料] 2025年运动会兄弟照.jpeg', 1446, 1920, 40);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (6, '2025年校运会', 'sports', '体育赛事', NULL, '组织参赛、人员联络、秩序安排和物资保障，为运动员顺利参赛提供支持。', '/media/activities/confirmed/school-sports-2025/01.jpeg', 60, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (5, 6, '/media/activities/confirmed/school-sports-2025/01.jpeg', 'image', '[确认资料] 25年校运会拔河照片.jpeg', 2844, 1600, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (6, 6, '/media/activities/confirmed/school-sports-2025/02.jpeg', 'image', '[确认资料] 25年校运会工作照片1.jpeg', 1600, 2133, 20);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (7, 6, '/media/activities/confirmed/school-sports-2025/03.jpeg', 'image', '[确认资料] 25年校运会群体聚餐照片.jpeg', 3554, 1600, 30);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (8, 6, '/media/activities/confirmed/school-sports-2025/04.jpeg', 'image', '[确认资料] 25年校运会偷懒照片.jpeg', 2132, 1599, 40);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (9, 6, '/media/activities/confirmed/school-sports-2025/05.mp4', 'video', '[确认资料] 25年校运会聚餐视频.mp4', NULL, NULL, 50);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (10, 6, '/media/activities/confirmed/school-sports-2025/06.mp4', 'video', '[确认资料] 25年校运会聚餐跳舞视频.mp4', NULL, NULL, 60);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (7, '新生杯', 'sports', '体育赛事', NULL, '组织和协助学院新生参加球类赛事，为同学提供展示与交流的平台。', NULL, 70, 0);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (8, '2025年部门生日会', 'birthday', '部门生日会', NULL, '在工作之外送上集体祝福，记录属于部门的温暖时刻。', '/media/activities/confirmed/birthday-2025/01.jpeg', 80, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (11, 8, '/media/activities/confirmed/birthday-2025/01.jpeg', 'image', '[确认资料] 2025年部门生日会群体照片.jpeg', 2133, 1600, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (12, 8, '/media/activities/confirmed/birthday-2025/02.jpeg', 'image', '[确认资料] 2025年部门生日会群体游戏照片1.jpeg', 1620, 1080, 20);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (13, 8, '/media/activities/confirmed/birthday-2025/03.jpeg', 'image', '[确认资料] 2025年部门生日会风景照片.jpeg', 1920, 1440, 30);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (14, 8, '/media/activities/confirmed/birthday-2025/04.jpeg', 'image', '[确认资料] 2025年部门生日会打麻将的照片.jpeg', 972, 647, 40);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (15, 8, '/media/activities/confirmed/birthday-2025/05.jpeg', 'image', '[确认资料] 2025年部门生日会蛋糕照片.jpeg', 1600, 2133, 50);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (16, 8, '/media/activities/confirmed/birthday-2025/06.jpeg', 'image', '[确认资料] 2025年部门生日会唱歌照片.jpeg', 1370, 2436, 60);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (17, 8, '/media/activities/confirmed/birthday-2025/07.jpeg', 'image', '[确认资料] 2025年部门生日会唱歌照片1.jpeg', 1370, 2436, 70);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (18, 8, '/media/activities/confirmed/birthday-2025/08.jpeg', 'image', '[确认资料] 2025年部门生日会三国杀群体游戏照片.jpeg', 647, 972, 80);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (19, 8, '/media/activities/confirmed/birthday-2025/09.jpeg', 'image', '[确认资料] 2025年部门生日会烧烤照片.jpeg', 1600, 2132, 90);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (20, 8, '/media/activities/confirmed/birthday-2025/10.mp4', 'video', '[确认资料] 2025年部门生日会唱歌视频.mp4', NULL, NULL, 100);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (9, '2025年体育部换届大会', 'meeting', '会议与学习', NULL, '总结阶段工作、完成工作交接，将经验与责任传递给新一届成员。', '/media/activities/confirmed/handover-2025/01.jpg', 90, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (21, 9, '/media/activities/confirmed/handover-2025/01.jpg', 'image', '[确认资料] 2025年换届大会群体照片.jpg', 1290, 836, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (22, 9, '/media/activities/confirmed/handover-2025/02.jpg', 'image', '[确认资料] 2025年换届大会部长小梦姐照片.jpg', 4096, 2304, 20);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (23, 9, '/media/activities/confirmed/handover-2025/03.mp4', 'video', '[确认资料] 2025年换届大会视频.mp4', NULL, NULL, 30);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (10, '紫荆花阳光跑', 'sports', '体育赛事', NULL, '组织春季阳光跑，做好名单确认、活动安排和现场协调。', NULL, 100, 0);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (11, '三月三民族运动会', 'sports', '体育赛事', NULL, '参与民族体育活动的组织与保障，让成员在真实任务中锻炼能力。', NULL, 110, 0);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (12, '电子杯', 'sports', '体育赛事', NULL, '结合班级和参赛人数制定赛程，保障赛事按计划开展。', NULL, 120, 0);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (13, '2025年团学素质拓展', 'team_building', '团建活动', NULL, '在协作任务中认识伙伴，提升沟通、组织与团队协作能力。', '/media/activities/confirmed/training-2025/01.jpeg', 130, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (24, 13, '/media/activities/confirmed/training-2025/01.jpeg', 'image', '[确认资料] 25团学素质拓展群体照片1.jpeg', 2133, 1600, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (25, 13, '/media/activities/confirmed/training-2025/02.jpeg', 'image', '[确认资料] 25团学素质拓展游戏照片1.jpeg', 1600, 2133, 20);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (14, '第三届部门生日会', 'birthday', '部门生日会', NULL, '第三届体育部成员共同庆祝和记录的部门生日会。', '/media/activities/confirmed/third-birthday/01.jpeg', 140, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (26, 14, '/media/activities/confirmed/third-birthday/01.jpeg', 'image', '[确认资料] 第三届部门生日会蛋糕照片.jpeg', 1600, 2844, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (27, 14, '/media/activities/confirmed/third-birthday/02.mp4', 'video', '[确认资料] 第三届部门生日会.mp4', NULL, NULL, 20);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (15, '2024年冬至活动', 'team_building', '团建活动', NULL, '成员一起包饺子、煮汤圆，在冬至活动中增进交流。', '/media/activities/confirmed/winter-solstice-2024/01.jpeg', 150, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (28, 15, '/media/activities/confirmed/winter-solstice-2024/01.jpeg', 'image', '[确认资料] 2024年冬至聚会群体照片.jpeg', 2133, 1600, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (29, 15, '/media/activities/confirmed/winter-solstice-2024/02.jpeg', 'image', '[确认资料] 2024年冬至饺子照片1.jpeg', 1600, 2133, 20);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (30, 15, '/media/activities/confirmed/winter-solstice-2024/03.jpeg', 'image', '[确认资料] 2024年冬至汤圆照片1.jpeg', 1600, 2133, 30);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (16, '2026年趣味活动', 'sports', '体育赛事', NULL, '通过轻松有趣的运动项目，让更多同学参与并感受运动乐趣。', '/media/activities/confirmed/fun-sports-2026/01.jpeg', 160, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (31, 16, '/media/activities/confirmed/fun-sports-2026/01.jpeg', 'image', '[确认资料] 2026年趣味活动.jpeg', 2125, 1600, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (32, 16, '/media/activities/confirmed/fun-sports-2026/02.jpeg', 'image', '[确认资料] 2026年趣味活动2.jpeg', 2125, 1600, 20);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (17, '2024年运动会', 'sports', '体育赛事', NULL, '记录体育部成员参与和保障运动会的集体时刻。', '/media/activities/confirmed/sports-2024/01.jpeg', 170, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (33, 17, '/media/activities/confirmed/sports-2024/01.jpeg', 'image', '[确认资料] 2024年运动会群体照片.jpeg', 2844, 1598, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (34, 17, '/media/activities/confirmed/sports-2024/02.mp4', 'video', '[确认资料] 2024年运动会聚餐视频.mp4', NULL, NULL, 20);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (18, '2024年部门生日会', 'birthday', '部门生日会', NULL, '记录2024年部门生日会的集体合影与共同回忆。', '/media/activities/confirmed/birthday-2024/01.jpeg', 180, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (35, 18, '/media/activities/confirmed/birthday-2024/01.jpeg', 'image', '[确认资料] 2024年部门生日群体照片.jpeg', 1560, 1170, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (36, 18, '/media/activities/confirmed/birthday-2024/02.jpeg', 'image', '[确认资料] 2024年部门生日烧烤照片.jpeg', 1440, 1920, 20);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (19, '2024年中秋团建', 'team_building', '团建活动', NULL, '成员在中秋团建中分享节日零食、交流近况，增进团队了解。', '/media/activities/confirmed/mid-autumn-2024/01.jpeg', 190, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (37, 19, '/media/activities/confirmed/mid-autumn-2024/01.jpeg', 'image', '[确认资料] 2024年中秋团建群体照片.jpeg', 2133, 1600, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (38, 19, '/media/activities/confirmed/mid-autumn-2024/02.jpeg', 'image', '[确认资料] 2024年中秋团建零食照片.jpeg', 2132, 1600, 20);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (39, 19, '/media/activities/confirmed/mid-autumn-2024/03.jpeg', 'image', '[确认资料] 2024年中秋团建零食照片2.jpeg', 2133, 1600, 30);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (20, '2024届迎新见面会', 'welcome', '迎新活动', NULL, '记录2024届迎新见面会的部门集体合影。', '/media/activities/confirmed/welcome-meeting-2024/01.jpeg', 200, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (40, 20, '/media/activities/confirmed/welcome-meeting-2024/01.jpeg', 'image', '[确认资料] 2024届迎新见面会群体照片.jpeg', 1920, 1440, 10);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (21, '2023年部门生日会', 'birthday', '部门生日会', NULL, '记录2023年部门生日会的集体合影和生日蛋糕。', '/media/activities/confirmed/birthday-2023/01.jpeg', 210, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (41, 21, '/media/activities/confirmed/birthday-2023/01.jpeg', 'image', '[确认资料] 2023年部门生日群体照片1.jpeg', 1440, 1080, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (42, 21, '/media/activities/confirmed/birthday-2023/02.jpeg', 'image', '[确认资料] 2023年部门生日群体照片2.jpeg', 1440, 1080, 20);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (43, 21, '/media/activities/confirmed/birthday-2023/03.jpeg', 'image', '[确认资料] 2023年部门生日群体照片3.jpeg', 2138, 1600, 30);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (44, 21, '/media/activities/confirmed/birthday-2023/04.jpeg', 'image', '[确认资料] 2023年部门生体蛋糕照片.jpeg', 1600, 2138, 40);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (22, '2023届运动会', 'sports', '体育赛事', NULL, '记录2023届运动会期间的赛事服务和部门集体时刻。', '/media/activities/confirmed/sports-2023/01.jpeg', 220, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (45, 22, '/media/activities/confirmed/sports-2023/01.jpeg', 'image', '[确认资料] 2023届运动会群体照片3.jpeg', 2846, 1600, 10);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (46, 22, '/media/activities/confirmed/sports-2023/02.jpeg', 'image', '[确认资料] 2023届运动会群体照片4.jpeg', 2400, 1600, 20);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (47, 22, '/media/activities/confirmed/sports-2023/03.jpeg', 'image', '[确认资料] 2023届运动会聚餐照片.jpeg', 2130, 1600, 30);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (23, '2023届新生见面会', 'welcome', '迎新活动', NULL, '通过新生见面会帮助新成员了解体育部并认识伙伴。', '/media/activities/confirmed/welcome-meeting-2023/01.jpeg', 230, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (48, 23, '/media/activities/confirmed/welcome-meeting-2023/01.jpeg', 'image', '[确认资料] 2023届见面会群体照片2.jpeg', 2133, 1600, 10);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (24, '2023届部门例会', 'meeting', '会议与学习', NULL, '记录部门成员沟通工作、明确分工和交流经验的例会。', '/media/activities/confirmed/meeting-2023/01.jpeg', 240, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (49, 24, '/media/activities/confirmed/meeting-2023/01.jpeg', 'image', '[确认资料] 2023届例会照片.jpeg', 1440, 1080, 10);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (25, '2022届新生见面会', 'welcome', '迎新活动', NULL, '记录2022届新生见面会的部门集体合影。', '/media/activities/confirmed/welcome-meeting-2022/01.jpeg', 250, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (50, 25, '/media/activities/confirmed/welcome-meeting-2022/01.jpeg', 'image', '[确认资料] 2022届新生见面会.jpeg', 1702, 1276, 10);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (26, '2022届部门例会', 'meeting', '会议与学习', NULL, '记录部门成员开展工作交流和任务讨论的例会。', '/media/activities/confirmed/meeting-2022/01.jpeg', 260, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (51, 26, '/media/activities/confirmed/meeting-2022/01.jpeg', 'image', '[确认资料] 2022届例会照片.jpeg', 2133, 1600, 10);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (27, '部门线上交流记录', 'other', '其他活动', NULL, '记录部门用于线上内容交流的平台入口；页面仅按用户提供的素材名称归档展示。', '/media/activities/confirmed/online-community/01.jpeg', 270, 1);
INSERT OR REPLACE INTO activity_media (id, activity_id, file, media_type, description, width, height, sort_order) VALUES (52, 27, '/media/activities/confirmed/online-community/01.jpeg', 'image', '[确认资料] 部门抖音群.jpeg', 750, 1072, 10);
INSERT OR REPLACE INTO activities (id, name, category, category_label, activity_date, introduction, cover, sort_order, is_visible) VALUES (28, '部门团建', 'team_building', '团建活动', NULL, '通过见面、协作和集体活动增进了解、凝聚感情。', NULL, 280, 0);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (1, '学院学生会有哪些部门？', '现有需求资料列出了组织部、团委秘书部、实践部、学检部、体育部、文艺部、外联部、全媒体中心和青年志愿者协会；具体名称以学院最新组织架构为准。', 10, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (2, '综合测评由什么组成？', '【需要学院确认】以下内容依据现有学校文件及学院修改校对材料整理，具体以学院当年正式通知和个人培养要求为准。

综合测评由德育、智育、体育、美育和劳动教育五部分组成。学校2022年正式办法规定，五部分占比分别为20%、50%、10%、10%和10%。', 20, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (3, '学院校对表中，德育活动具体怎样计分？', '【需要学院确认】以下内容依据现有学校文件及学院修改校对材料整理，具体以学院当年正式通知和个人培养要求为准。

学院2026修改校对材料拟定：认可的校级、院级德育活动参加5次且至少1次为院级活动，思想品德表现基础分为100分；4次90分、3次80分、2次70分、1次60分。认可活动另拟按0.2分/次计入德育加分，德育加分总额不超过20分。', 30, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (4, '体育部任职具体能加多少分？', '【需要学院确认】以下内容依据现有学校文件及学院修改校对材料整理，具体以学院当年正式通知和个人培养要求为准。

学校正式办法规定，院学生会执行主席4.5分、主席团成员4分、部门主要负责人3分、部门其他工作人员2.5分、干事1分，须任职满1学期、认真履职并考核合格。学院修改校对表对身兼数职另有拟定认定规则。', 40, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (5, '参加体育活动具体怎样计分？', '【需要学院确认】以下内容依据现有学校文件及学院修改校对材料整理，具体以学院当年正式通知和个人培养要求为准。

学院修改校对表拟定了校级、院级竞赛类体育活动、跑步活动和观众参与的分值，并对报名后无故缺席设置扣分。所有项目须以学院出具的证明和当年正式通知为准。', 50, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (6, '体育比赛获奖具体加多少分？', '【需要学院确认】以下内容依据现有学校文件及学院修改校对材料整理，具体以学院当年正式通知和个人培养要求为准。

学校正式办法规定：自治区级及以上比赛前八名依次加18至11分；市、校级运动会前八名依次加10至3分；学院赛事前八名依次加4至0.5分。体育加分最高20分，同一次比赛多项名次只取最高分，集体项目个人加分减半。', 60, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (7, '学习和科技竞赛获奖具体加多少分？', '【需要学院确认】以下内容依据现有学校文件及学院修改校对材料整理，具体以学院当年正式通知和个人培养要求为准。

现有办法列出了国家级、自治区级、市校级和学院级竞赛分值，智育加分最高20分。学院修改校对材料还对认可赛事范围、团队排序递减和同赛项不重复加分作了拟定说明。', 70, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (8, '志愿服务具体怎样计入劳育？', '【需要学院确认】以下内容依据现有学校文件及学院修改校对材料整理，具体以学院当年正式通知和个人培养要求为准。

学院修改校对材料拟定了志愿时数基础分、超过8小时后的加分和星级志愿者分值，其中额外时数加分上限为10分。', 80, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (9, '第二课堂各学年具体要求是多少？毕业需要多少分？', '【需要学院确认】以下内容依据现有学校文件及学院修改校对材料整理，具体以学院当年正式通知和个人培养要求为准。

学院修改校对表拟定：相应学年各模块达到大一2.5学分、大二5学分、大三7.5学分时，德育加3分。现有材料没有写明毕业所需第二课堂总学分，毕业要求不能据此确定。', 90, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (10, '荣誉称号怎样加分，能重复计算吗？', '【需要学院确认】以下内容依据现有学校文件及学院修改校对材料整理，具体以学院当年正式通知和个人培养要求为准。

学校办法规定了不同级别个人荣誉分值。学院修改校对材料注明个人先进荣誉不重复计同类最高项，集体荣誉与个人荣誉可按规则累计，荣誉相关总分不超过10分；奖学金类证书和勤工助学奖不作为荣誉加分。', 100, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (11, '综合测评和奖学金、评奖评优有什么关系？', '【需要学院确认】以下内容依据现有学校文件及学院修改校对材料整理，具体以学院当年正式通知和个人培养要求为准。

学校正式办法明确，每学年综合测评平均分是评优评先的重要依据。现有材料没有规定具体奖学金金额，也没有给出某类奖学金的固定综测门槛。', 110, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (12, '为什么加入体育部？', '这里有赛事组织的实践机会，也有往届学长学姐的经验传承。你可以认识伙伴，并在一次次活动中提升沟通、组织和协作能力。', 120, 1);
INSERT OR REPLACE INTO faqs (id, question, answer, sort_order, is_visible) VALUES (13, '没有体育特长也可以报名吗？', '可以。体育部工作包括策划、组织、协调和现场保障，更看重责任心、沟通能力与参与热情。', 130, 1);
